// Generated by dts-bundle-generator v9.5.1

import React$1 from "react";

export type Data =
  | FormData
  | {
      [key: string]: any;
    };
export interface FormProps extends Omit<
  React$1.FormHTMLAttributes<HTMLFormElement>,
  "onError"
> {
  onSubmit: (data: Data) => any | Promise<any>;
  onError?: (error: Error) => any | Promise<any>;
  onChange?: (data: Data) => any;
  autoReset?: boolean;
}
export type FormErrorChildren =
  | React$1.ReactNode
  | ((message: string, error: Error) => React$1.ReactNode);
export interface FormErrorProps {
  children?: FormErrorChildren;
}
export type FormLoadingChildren =
  | React$1.ReactNode
  | ((loading: boolean) => React$1.ReactNode);
export interface FormLoadingProps {
  children?: FormLoadingChildren;
}
export interface FormContextType {
  loading: boolean;
  error: Error | false;
  handled: React$1.MutableRefObject<boolean>;
}
export declare const FormContext: React$1.Context<FormContextType>;
export declare function FormError({
  children,
}: FormErrorProps): React$1.ReactNode;
export declare function FormLoading({
  children,
}: FormLoadingProps): React$1.ReactNode;
declare function Form({
  onSubmit,
  onError,
  onChange,
  autoReset,
  children,
  ...props
}: FormProps): JSX.Element;

export { Form as default };

export {};
